services:
    # LOKI SERVICE
    loki:
        image: grafana/loki:2.9.0
        ports:
            - "3100:3100"
        volumes:
            - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
            - ./loki:/loki
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - dalam-kemasan-network

    promtail:
        image: grafana/promtail:2.9.0
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./promtail/config.yaml:/etc/promtail/config.yaml
            - ./promtail:/etc/promtail
            - ./service/var/log/service:/var/log/service
        command: -config.file=/etc/promtail/config.yaml
        networks:
            - dalam-kemasan-network
        
    # prometheus
    prometheus:
        image: prom/prometheus:v2.43.0
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus:/prometheus
        networks:
            - dalam-kemasan-network
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'

    grafana: 
        image: grafana/grafana:10.2.2
        ports:
            - "${GRAFANA_PORT}:${GRAFANA_PORT}"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_AUTH_ANONYMOUS_ENABLED=false
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
            - GF_AUTH_ANONYMOUS_ORG_ID=1
        networks:
            - dalam-kemasan-network
        volumes:
            - grafana-storage:/var/lib/grafana
    # service
    # Database for the service
    service-db:
        image: postgres:17.2-alpine
        env_file:
            - service/.env
        volumes:
            - ./service/db/init.sql:/docker-entrypoint-initdb.d/init.sql # init script
            - service-data:/var/lib/postgresql/data
        networks:
            - dalam-kemasan-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U dalamKemasan -d auth_service_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    # API for the service
    service-api:
        build: ./service
        env_file:
            - service/.env
            - .env
        depends_on:
            service-db:
                condition: service_healthy # Ensure DB is ready
        volumes:
          - ./service/var/log/service:/var/log/service
        networks:
            - dalam-kemasan-network
        ports:
            - ${SERVICE_PORT}:${SERVICE_PORT}

    minio:
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        ports:
            - "9001:9001" # API port
            - "9000:9000" # Console port
        volumes:
            - minio-data:/data
        env_file:
            - service/.env # Assuming MINIO_ROOT_USER and MINIO_ROOT_PASSWORD are in this file
        command: server /data --console-address ":9001"
        networks:
            - dalam-kemasan-network

networks:
    dalam-kemasan-network:
        external: true

# volumes for persistent data
volumes:
    service-data:
    grafana-storage:
    loki-data:
    prometheus-data:
    minio-data: