apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: dalam-kemasan
data:
  PORT: "8081"
  CORS_URL: "http://localhost:3000,http://localhost:5173"
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  ACCESS_TOKEN_DURATION_MINUTES: "15"
  REFRESH_TOKEN_DURATION_HOURS: "168"
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET_NAME: "dalam-kemasan-files"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dalam-kemasan
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service:8081']
        metrics_path: '/metrics'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: dalam-kemasan
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: dalam-kemasan
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
      - job_name: containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: containerlogs
              __path__: /var/log/*.log
