apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: dalam-kemasan
type: Opaque
stringData:
  DB_URL: "postgresql://dalamKemasan:securepassword123@postgres-service:5432/auth_service_db?sslmode=disable"
  JWT_ACCESS_SECRET: "your-super-secret-jwt-key-here-change-this"
  REFRESH_TOKEN_SECRET_KEY: "your-super-secret-refresh-key-here-change-this"
  MINIO_ACCESS_KEY_ID: "minioadmin"
  MINIO_SECRET_ACCESS_KEY: "minioadmin123"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin123"
  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dalam-kemasan
type: Opaque
stringData:
  POSTGRES_DB: "auth_service_db"
  POSTGRES_USER: "dalamKemasan"
  POSTGRES_PASSWORD: "securepassword123"
