import type { Metadata } from "next";
import "./globals.css";
import { body, heading } from "@/lib/fonts";

export const metadata: Metadata = {
	title: "Dalam Kemasan",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body
				className={`${body.className} ${heading.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
